### PR TITLE
Jupyter report

### PR DESCRIPTION
**Pull request by jeanlouisboudart**
This PR basically add some python script to produce CSV files for all producer implementations and then use Jupiter to generate markdown report in results/${SCENARIO}/report.md.

In addition to this there is a new script call `run-jupiter.sh` that start jupiter web-ui on http://localhost:8888, so you can hack and play with the notebooks.

### CODE REVIEW

**Comment by jeanlouisboudart** [comment]
@aesteve would you mind reviewing this ?

**Comment by aesteve** [comment]
To be fixed, still: 

```
utils.sh: line 5: realpath: command not found
```
Workaround on Mac OS: `brew install coreutils`

**Comment by jeanlouisboudart** [comment]
@aesteve I've pushed a commit to get rid of realpath.
This should help in term of portability, we used the same trick within jmx-monitoring-stacks so I'm confident on the path.

Please let me know how it runs on mac.

**Comment by aesteve** [comment]
Seems to work without issue.

**Pull request merged**
